[package]
name = "betterplayer"
version = "0.1.0"
edition = "2018"
authors = ["Tobias de Bruijn <t.debruijn@signin.array21.dev"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19.0"
log4j = "0.1.0"
lazy_static = "1.4.0"
fon = "0.5.0"
espeakng-sys = "0.1.0"
libc = "0.2.102"